### ISSUE TITLE
Add processor check to scripts

### ISSUE THREAD

**Issue by fuzzywalls** [fuzzywalls/ghidra_scripts#12]
Add processor checks to scripts that only work on certain architectures. Scripts such as MipsRopX that only support the MIPS processor should not be allowed to run against an ARM binary.

**Comment by astrelsky** [comment]
This should be relatively simple to do. An example of checking for MIPS may be found in the [MIPS constant reference analyzer](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/MIPS/src/main/java/ghidra/app/plugin/core/analysis/MipsAddressAnalyzer.java)

However,  checking exactly this way will prevent some variants such as the ghidra-emotionengine from passing this check. I'm not sure if it even applies there or not though.

**Comment by fuzzywalls** [comment]
Forgot to add the fix in the commit, but it was addressed in this commit: d0d2eef2fb6f00e45a505283c187ce38e33c5491.  Addressed it by checking the processor via `currentProgram.getLanguage().getProcessor().toString()` and comparing that against supported processors.
