### ISSUE TITLE
Fluorescence Indirect Function Call Decompilation.

### ISSUE THREAD

**Issue by astrelsky** [fuzzywalls/ghidra_scripts#4]
Just a question in regards to the example image for Fluorescence with the indirect jr t9 call to time. Does it show up as a call to time in the decompiled output or only in the disassembly reference?

**Comment by fuzzywalls** [comment]
The calls will only be highlighted in the disassembly view and not in the decompiled output. The could be an interesting feature to add. I'd have to do some research and see if that ability is exposed through the scripting API.

**Comment by astrelsky** [comment]
> The calls will only be highlighted in the disassembly view and not in the decompiled output. The could be an interesting feature to add. I'd have to do some research and see if that ability is exposed through the scripting API.

I see. I asked because if it did I wanted to know how you managed to achieve it. I would have then tried to use a similar approach for virtual member accessing in my [Ghidra C++ Class Analyzer](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer). No worries though, I don't think it is possible to do yet unless it is a call to a function within a vftable. If it is then creating a structure for the vftable will allow the decompiler to show it as a function call to the structure member. This goes for not just the scripting API but the entire java API.
