### ISSUE TITLE
Differences in Pointer Size

### ISSUE THREAD

**Issue by astrelsky** [fuzzywalls/ghidra_scripts#7]
I noticed you're using Pointer32DataType in 96ecab2dd9bc71423f21addc99edfc6d9e500bb2. This is a fixed size pointer and might only work on processors with a 32-bit pointer size. Initializing it like so may solve this restriction.

`pointer_type = PointerDataType(None, currentProgram.getDefaultPointerSize())`

Passing in None or null as the DataType in the PointerDataType constructor will construct a default pointer without a DataType.

You might need to watch out for data existing between the currentAddress and the length of the default pointer size. Sticking to the pointer size alignment may help with this. It may be retrieved via
`pointer_alignment = currentProgram.getDataTypeManager().getDataOrganization().getDefaultPointerAlignment()`

**Comment by fuzzywalls** [comment]
Thanks for the ticket. I added a function to dynamically retrieve the pointer type. There is no need to check for data existing between the current address and the length of the pointer because the call to createData will throw an exception if data is already defined in that range.

**Comment by astrelsky** [comment]
> Thanks for the ticket. I added a function to dynamically retrieve the pointer type. There is no need to check for data existing between the current address and the length of the pointer because the call to createData will throw an exception if data is already defined in that range.

I see that should be good enough. What about alignment though? Its possible to get a valid address from the intersection of two contiguous ints for example. It may be a valid address but its not actually a pointer.

I haven't seen the issue yet since I haven't tested since the changes, its just a thought.

**Comment by fuzzywalls** [comment]
Yea that is possible. I also check that there is a valid reference to that pointer and if no reference is found I remove the pointer cast.

**Comment by astrelsky** [comment]
> Yea that is possible. I also check that there is a valid reference to that pointer and if no reference is found I remove the pointer cast.

Oh ok excellent thank you. 

These scripts are great keep up the good work!
